services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.hu
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ../config/pgadmin/servers.json:/pgadmin4/servers.json
networks:
  foldsight-network:
    driver: bridge
